language: node_js

node_js:
  - "lts/*" # 10 (Latest LTS)
  - "node" # 12 (Latest Stable)

matrix:
  include:
    - # Linting stage
      node_js: "lts/*" # Latest LTS
      script: npm run lint

cache: npm

script:
  - npm run coverage
